
name: Auth Service CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:


permissions:
  contents: write    
  packages: write   
  security-events: write

jobs:
  ci:
    name: Auth Service Pipeline
    uses: FanVault-Merchh/FanVault-shared-workflows/.github/workflows/service-ci.yml@main
    with:

      service-name: auth-service


      image-name: savitxr/fanvault-auth

      helm-repo: FanVault-Merchh/helm-charts


      helm-values-path: fanvault-micro-apps/charts/auth-service/values.yaml

      working-directory: '.'

    secrets: inherit

